apiVersion: apps/v1
kind: Deployment
metadata:
  name: depoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      containers:
        - name: ope1
          image: khero1234/operator:1234
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
         